### ISSUE TITLE
Gettng an error on Windows 10 x64

### ISSUE THREAD

**Issue by rjbprime** [noahlange/markwright-app#3]
Using Git 2.21.0 x64 and Node version 10.15.3 x64.

After following the instructions to build the app on Windows 10 x64, I double click on the Markwright Setup 0.7.2.exe, it installs, then comes up with an error,

```
Uncaught Exception:
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (69).
For more information on which environments are supported please see https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports
(C:/Users/<username>/AppData/Local/Programs/Markwright/resources/app.asr/node_mod...:13)
    at Object.<anonymous>
(C:/Users/<username>/AppData/Local/Programs/Markwright/resources/app.asr/node_mod...:35)
    at Object.<anonymous>
(C:/Users/<username>/AppData/Local/Programs/Markwright/resources/app.asr/node_mod...:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions (internal/modules/cjs/loader.js:704:10)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

If I go into the win-unpacked folder, and run the Markwright exe there, same error.

Is this app only for MacOS, or is it Windows / Linux compatible as well?

**Comment by noahlange** [comment]
Interesting. It *should* be Windows compatible, I got it to build/run a few weeks ago.

What Windows version are you running?

**Comment by rjbprime** [comment]
x64, Version 1809 17763.379.

**Comment by rjbprime** [comment]
On a week old install of Windows x64, 1809 version 17763.437, with most recent versions of Git (Git-2.21.0-64-bit) and Node (node-v12.1.0-x64), both installed 30 minutes before this post.. I'm getting an error in the logs regarding the node-sass version 4.11.0 post install script failing.

Above that error in the log it says that verbose node v12.1.0, npm v6.9.0, errno 1, error code ELIFECYCLE. Could the version of node-sass linked to the code be out of date, the version of Node installed be too current? Or is the version you used in your coding be an older, out of service version? Just spitballing here.

My logs are attached, with username scrubbed.
[2019-05-05T10_06_15_042Z-debug.log](https://github.com/noahlange/markwright-app/files/3145404/2019-05-05T10_06_15_042Z-debug.log)
[2019-05-05T10_08_02_111Z-debug.log](https://github.com/noahlange/markwright-app/files/3145405/2019-05-05T10_08_02_111Z-debug.log)
[2019-05-05T10_09_05_154Z-debug.log](https://github.com/noahlange/markwright-app/files/3145406/2019-05-05T10_09_05_154Z-debug.log)

**Comment by rjbprime** [comment]
Any update on this?

**Comment by rjbprime** [comment]
Looking to try to start using this app. Is there any updates on how to get this to work on Windows 10?

**Comment by noahlange** [comment]
Hey. I took a gander and (eventually) got it working on my Windows install. If you clone the repo, you should be able to build it and run it without (immediate) issues.

```bash
# clone and install
git clone https://github.com/noahlange/markwright-app.git
cd markwright-app && yarn

# generate executable
yarn run dist

# dev mode
yarn run build && yarn start
```
Let me know if you run into any more issues. I'll try to be a little more prompt in getting back to you.

**Comment by rjbprime** [comment]
So what is the difference between npm and yarn? Is yarn a separate install?

**Comment by rjbprime** [comment]
Managed to get the app to run, but now it seems to be failing to save on Windows 10. On another note, I've looked at the markwright-app site, is there an example of how to write content?

**Comment by noahlange** [comment]
Yeah, the rewrite of file operations was WIP/borked. I've fixed up the errors I've encountered on MacOS, but haven't yet gotten a chance to test on Windows.

Docs are very old and pretty useless at the moment. Your best bet for now would be the [commonmark docs](https://commonmark.org) and [SASS basics](https://sass-lang.com/guide). That's assuming you're familiar with CSS—if not, the [MDN has a good primer](https://developer.mozilla.org/en-US/docs/Web/CSS).

In order to figure out what to target with CSS, you can hover over any element and hold down "alt" to get the tag + classes.
